<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Gedung Bertingkat Disewa</name>
   <tag></tag>
   <elementGuidId>0845f01b-715a-4de7-a18a-1db6fc2d537e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;gedung bertingkat disewa&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[3]/div/div[2]/div/a[13]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>87d68dfe-c561-4c86-be2e-3a13a6929288</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.99.co/id/sewa/gedung-bertingkat</value>
      <webElementGuid>ad5302fb-dc32-4def-a4bd-2623380012b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>gedung bertingkat disewa</value>
      <webElementGuid>a2ae8f2e-2636-4dfb-817a-7c9dda7799ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Gedung Bertingkat Disewa</value>
      <webElementGuid>02067391-3faa-4dd2-a4e4-76a0896dff73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;upperFooter&quot;]/div[@class=&quot;upperFooter__container&quot;]/div[@class=&quot;accordion&quot;]/div[@class=&quot;accordion-content showContent&quot;]/a[13]</value>
      <webElementGuid>08e6986f-b045-45de-9644-2b2fce8bb252</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[3]/div/div[2]/div/a[13]</value>
      <webElementGuid>505f8250-54fb-44bf-9dd3-8dfc2933ae0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Gedung Bertingkat Disewa')]</value>
      <webElementGuid>d10933ec-0f51-4bda-8fb2-d1740bb49781</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://www.99.co/id/sewa/gedung-bertingkat')])[2]</value>
      <webElementGuid>9522d559-e53c-467b-9b39-461e0410e0f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/a[13]</value>
      <webElementGuid>d072d83c-d05b-4101-9570-52f83c30a03d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.99.co/id/sewa/gedung-bertingkat' and @title = 'gedung bertingkat disewa' and (text() = 'Gedung Bertingkat Disewa' or . = 'Gedung Bertingkat Disewa')]</value>
      <webElementGuid>22ff7deb-15de-487c-8743-c5359fa99316</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
