<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Komersial Disewa</name>
   <tag></tag>
   <elementGuidId>4f314620-8b37-4c67-b910-4a3999424264</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;komersial disewa&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[3]/div/div[2]/div/a[7]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4657c7c7-675c-4a14-943b-06b9063410b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.99.co/id/sewa/komersial</value>
      <webElementGuid>d3999d0c-1fad-4fad-9c19-196071e09ab2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>komersial disewa</value>
      <webElementGuid>c44f0838-1a1e-487d-9c1a-736a5231bbdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Komersial Disewa</value>
      <webElementGuid>ac6c894a-a4df-48a0-9e3f-4ffb8093e5f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;upperFooter&quot;]/div[@class=&quot;upperFooter__container&quot;]/div[@class=&quot;accordion&quot;]/div[@class=&quot;accordion-content showContent&quot;]/a[7]</value>
      <webElementGuid>3b31d950-bb08-49fe-aafc-a15c41da8ab7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[3]/div/div[2]/div/a[7]</value>
      <webElementGuid>5874d0a1-2cbc-4124-8d77-2b3d8a5934b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Komersial Disewa')]</value>
      <webElementGuid>4c579efc-c71e-4527-934c-ffecbdd85fdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://www.99.co/id/sewa/komersial')])[2]</value>
      <webElementGuid>4f957fcc-960f-4642-b937-e1628abef982</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/a[7]</value>
      <webElementGuid>7a8ea7a0-ec22-4f60-a426-7ff357b2bc2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.99.co/id/sewa/komersial' and @title = 'komersial disewa' and (text() = 'Komersial Disewa' or . = 'Komersial Disewa')]</value>
      <webElementGuid>cf94ecc4-6bd1-41d1-8eea-fb80d7a845ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
