<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Pabrik Disewa</name>
   <tag></tag>
   <elementGuidId>95e82091-b411-49dd-bcdd-d48093684689</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;pabrik disewa&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[3]/div/div[2]/div/a[12]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>dac38b67-ab89-4597-b3e6-448256b82a8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.99.co/id/sewa/pabrik</value>
      <webElementGuid>775f1341-2da4-4dc0-8f34-a4c716223501</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>pabrik disewa</value>
      <webElementGuid>e89f8424-e9b1-4117-8bc9-5e1853377065</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pabrik Disewa</value>
      <webElementGuid>54b115c3-4d78-4896-8dcf-f0fe6fc414bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;upperFooter&quot;]/div[@class=&quot;upperFooter__container&quot;]/div[@class=&quot;accordion&quot;]/div[@class=&quot;accordion-content showContent&quot;]/a[12]</value>
      <webElementGuid>2cfb76e2-3f74-454b-afcc-404f7f35a9f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[3]/div/div[2]/div/a[12]</value>
      <webElementGuid>bc3f20ba-44f8-4341-a884-6d440c475a25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Pabrik Disewa')]</value>
      <webElementGuid>e931c5bc-58a3-499a-807b-1aa7af593292</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://www.99.co/id/sewa/pabrik')])[2]</value>
      <webElementGuid>d2d9f2ac-a4e6-434d-9e7a-bab24f9d07c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/a[12]</value>
      <webElementGuid>e5ce9cb7-040c-4183-9715-0022e7ea3465</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.99.co/id/sewa/pabrik' and @title = 'pabrik disewa' and (text() = 'Pabrik Disewa' or . = 'Pabrik Disewa')]</value>
      <webElementGuid>c38efbbd-af65-4ad7-b898-d52157bed203</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
