<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Ruang Kantor Disewa</name>
   <tag></tag>
   <elementGuidId>f998cf13-a649-438b-887f-25b975983f6b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;ruang kantor disewa&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[3]/div/div[2]/div/a[8]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>94fcd7b5-8579-41f5-bebe-cf92fe93d109</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.99.co/id/sewa/ruang-kantor</value>
      <webElementGuid>2173e21b-b369-4b33-b8b6-188831696668</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>ruang kantor disewa</value>
      <webElementGuid>04d1a30f-d5a4-4ec8-b2b8-e1ee8aecf299</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ruang Kantor Disewa</value>
      <webElementGuid>57e35c59-ebe1-4609-aca4-9d97a923b0b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;upperFooter&quot;]/div[@class=&quot;upperFooter__container&quot;]/div[@class=&quot;accordion&quot;]/div[@class=&quot;accordion-content showContent&quot;]/a[8]</value>
      <webElementGuid>0ed35141-5576-41d3-b851-ea5c1ffc6423</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[3]/div/div[2]/div/a[8]</value>
      <webElementGuid>6e4e0d0b-9827-4fa9-9815-878be95b83f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Ruang Kantor Disewa')]</value>
      <webElementGuid>dfd5fa35-270e-4915-b05f-5b29cc46267e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://www.99.co/id/sewa/ruang-kantor')])[2]</value>
      <webElementGuid>a1c26be4-f969-4f5c-87e6-7fcb93d29a87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/a[8]</value>
      <webElementGuid>8850276d-9e0d-486d-990c-b1738d89a23e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.99.co/id/sewa/ruang-kantor' and @title = 'ruang kantor disewa' and (text() = 'Ruang Kantor Disewa' or . = 'Ruang Kantor Disewa')]</value>
      <webElementGuid>e13212c2-19bb-4832-99ea-dfeae6a7ed21</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
