<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Toko Disewa</name>
   <tag></tag>
   <elementGuidId>2caf3907-fb71-4b01-ac6f-baffe8b0bfbc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;toko disewa&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[3]/div/div[2]/div/a[15]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>394e6e57-ea18-445a-aa0b-47db453384d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.99.co/id/sewa/toko</value>
      <webElementGuid>f8368f9e-031c-41bd-877e-14ed47360fce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>toko disewa</value>
      <webElementGuid>6ee3fa50-8a6e-4ac0-bedb-d9f764a210d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Toko Disewa</value>
      <webElementGuid>47b0242e-494b-495f-b983-7be714ac8485</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;upperFooter&quot;]/div[@class=&quot;upperFooter__container&quot;]/div[@class=&quot;accordion&quot;]/div[@class=&quot;accordion-content showContent&quot;]/a[15]</value>
      <webElementGuid>787a7940-f22c-4b4c-b27e-bacec5675a49</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[3]/div/div[2]/div/a[15]</value>
      <webElementGuid>17e5d6ae-a618-4643-9850-b62ccea4279e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Toko Disewa')]</value>
      <webElementGuid>f3b169f3-2a71-4832-a412-64ac66e9d805</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://www.99.co/id/sewa/toko')])[2]</value>
      <webElementGuid>ce938896-c185-4cb4-bc4c-b6dd8d4eacbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/a[15]</value>
      <webElementGuid>2958f024-5c70-4eae-a2ef-1ca43e3627ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.99.co/id/sewa/toko' and @title = 'toko disewa' and (text() = 'Toko Disewa' or . = 'Toko Disewa')]</value>
      <webElementGuid>edfbd7ab-aa9a-4a6c-8f44-32898a202d0c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
