<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_500</name>
   <tag></tag>
   <elementGuidId>c71c67d3-18b2-4e6b-a198-cbdd86918a19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div/div/div/div[4]/div[30]/div[2]/button[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5027d276-1e2e-4d96-96af-31765efd4dc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-atomic-pagination__item</value>
      <webElementGuid>f71ab18d-5dcf-43fb-9d5b-7b7ea68e49be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>ab913eb4-1882-4260-8264-3a41e295b50f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;ui-srp&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-main col-12 col-xl-9&quot;]/div[@class=&quot;srpListing&quot;]/div[@class=&quot;ui-atomic-pagination&quot;]/div[@class=&quot;ui-atomic-pagination__page&quot;]/button[@class=&quot;ui-atomic-pagination__item&quot;]</value>
      <webElementGuid>0b080b1c-8b97-4074-8bde-6fbb43283eee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/div/div/div[4]/div[30]/div[2]/button[6]</value>
      <webElementGuid>03793484-ed57-42a1-9c8f-59cf98c57cf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button[6]</value>
      <webElementGuid>7d0b11bf-7c66-4f80-8408-46d5e363b391</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '500' or . = '500')]</value>
      <webElementGuid>52e028e7-d59b-4f88-beca-693497013fd6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
