<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Jawa BaratProvinsi Di IndonesiaProvinsi</name>
   <tag></tag>
   <elementGuidId>244e3344-c8fd-4c08-ac9f-331c6d671be3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;Jawa &lt;strong>Ba&lt;/strong>rat&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/section/form/div[2]/div[2]/div[2]/div[2]/div/a[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>572b03b9-120c-4a94-a767-fba689be0ca0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.99.co/id/jual/rumah/jawa-barat</value>
      <webElementGuid>e02a5b67-4997-4c7e-9350-0706881959c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Jawa &lt;strong>Ba&lt;/strong>rat</value>
      <webElementGuid>a7bf5e02-8ed3-471a-b1a2-da4013927854</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Jawa BaratProvinsi Di IndonesiaProvinsi</value>
      <webElementGuid>69a9147b-17ea-454d-bf5c-0a63af0ecb7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;homePage&quot;]/section[@class=&quot;banner&quot;]/form[@class=&quot;searchBarHome&quot;]/div[@class=&quot;searchBarHome--main&quot;]/div[@class=&quot;searchBarHome--main__col&quot;]/div[@class=&quot;ui-molecules-search-bar&quot;]/div[@class=&quot;ui-molecules-search-bar__suggestions&quot;]/div[@class=&quot;ui-molecules-search-bar__suggestions-wrapper&quot;]/a[3]</value>
      <webElementGuid>2cb8ce2c-c508-4749-aba2-448a70c10c14</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section/form/div[2]/div[2]/div[2]/div[2]/div/a[3]</value>
      <webElementGuid>2587eeed-1fee-467b-b758-199a049d700e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.99.co/id/jual/rumah/jawa-barat')]</value>
      <webElementGuid>a6912e61-a559-46a0-9c28-4955b10040d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div/a[3]</value>
      <webElementGuid>b095967f-ea18-41dd-a011-78f95d503d2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.99.co/id/jual/rumah/jawa-barat' and @title = 'Jawa &lt;strong>Ba&lt;/strong>rat' and (text() = 'Jawa BaratProvinsi Di IndonesiaProvinsi' or . = 'Jawa BaratProvinsi Di IndonesiaProvinsi')]</value>
      <webElementGuid>30dd214f-a3a7-4ef4-bad2-44d44c2ec444</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
