<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Cari Properti</name>
   <tag></tag>
   <elementGuidId>1d4e9334-20d8-4a15-98ea-6d3fe3470e48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.searchBarHome--submit.ui-atomic-button.ui-atomic-button__size-default.ui-atomic-button__theme-primary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8b1dbcb3-0db8-4ca6-abf7-67750a1e1a72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a5716d2d-8f6f-469f-816d-1ecde0d7dc86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>searchBarHome--submit ui-atomic-button ui-atomic-button__size-default ui-atomic-button__theme-primary</value>
      <webElementGuid>b8850b49-b99c-4080-a490-58962ea19c46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cari Properti</value>
      <webElementGuid>bb35d5fd-6dd6-4899-9c63-d54bf1655f2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;homePage&quot;]/section[@class=&quot;banner&quot;]/form[@class=&quot;searchBarHome&quot;]/div[@class=&quot;searchBarHome--main&quot;]/button[@class=&quot;searchBarHome--submit ui-atomic-button ui-atomic-button__size-default ui-atomic-button__theme-primary&quot;]</value>
      <webElementGuid>fc95d9cd-5a7d-4ad6-9d54-5d51995eadcd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[3]</value>
      <webElementGuid>1a4b553d-e690-432d-9b12-dece74240d8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section/form/div[2]/button</value>
      <webElementGuid>e2de3ab1-ddf9-4b3e-a6d9-ffacd3620619</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/button</value>
      <webElementGuid>c43d3746-fc0d-46c2-aa33-37a7fac5d584</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Cari Properti' or . = 'Cari Properti')]</value>
      <webElementGuid>c40628d0-2b25-488c-acc8-5d6de6f1d55e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
