<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_apartment</name>
   <tag></tag>
   <elementGuidId>5ed4cbe4-1385-4e98-abec-f3be84991a71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.field-option.field-option--2.truncated</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/section/form/div[2]/div/div[2]/ul/li[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>a30453a0-26b0-4c4b-b0e9-050515309de8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>field-option field-option--2 truncated</value>
      <webElementGuid>e3aa9453-7e60-461d-b97f-da0db6b59e39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>apartment</value>
      <webElementGuid>b7a2f2ab-ff8d-455f-9922-42dd0573f436</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;homePage&quot;]/section[@class=&quot;banner&quot;]/form[@class=&quot;searchBarHome&quot;]/div[@class=&quot;searchBarHome--main&quot;]/div[@class=&quot;searchBarHome--main__col&quot;]/div[@class=&quot;ui-molecules-select searchBarHome--main__filter_select&quot;]/ul[@class=&quot;ui-molecules-select__field-options ui-molecules-select__field-options-position-bottom&quot;]/li[@class=&quot;field-option field-option--2 truncated&quot;]</value>
      <webElementGuid>d84a8b7f-223e-4759-b97d-3870acadc5ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section/form/div[2]/div/div[2]/ul/li[2]</value>
      <webElementGuid>a52a2637-c2f3-466f-b876-2a4d79d12e86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]</value>
      <webElementGuid>d792c3d0-dd0f-4c96-9653-2893a155778d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'apartment' or . = 'apartment')]</value>
      <webElementGuid>ca7ca7aa-1068-46b5-8260-14cda2b8bb80</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
