<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Gedung Bertingkat Dijual</name>
   <tag></tag>
   <elementGuidId>13a7546f-4227-4364-bfa0-5fecee231216</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;gedung bertingkat dijual&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[3]/div/div/div/a[13]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>25e59ddb-70ee-47f3-939a-afb9f7a8a7d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.99.co/id/jual/gedung-bertingkat</value>
      <webElementGuid>b9498d44-1281-4f52-81dd-488cb901e855</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>gedung bertingkat dijual</value>
      <webElementGuid>f0431de9-c49d-408d-a279-215e93776e14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Gedung Bertingkat Dijual</value>
      <webElementGuid>159c51b4-1e19-4901-8510-1fa7f226f4d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;upperFooter&quot;]/div[@class=&quot;upperFooter__container&quot;]/div[@class=&quot;accordion&quot;]/div[@class=&quot;accordion-content showContent&quot;]/a[13]</value>
      <webElementGuid>9c7cedd7-5daa-481b-99bd-07e87274fc73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[3]/div/div/div/a[13]</value>
      <webElementGuid>64f8b5ec-2137-4c05-ba72-2ed1803be031</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Gedung Bertingkat Dijual')])[2]</value>
      <webElementGuid>c2f9bbe4-93e1-4523-a021-0e66535f89ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://www.99.co/id/jual/gedung-bertingkat')])[2]</value>
      <webElementGuid>ffe394b0-3756-4f7b-b0e5-4a9de6fd6d2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/a[13]</value>
      <webElementGuid>7646f8b8-9325-42f5-ab2c-3f32920050c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.99.co/id/jual/gedung-bertingkat' and @title = 'gedung bertingkat dijual' and (text() = 'Gedung Bertingkat Dijual' or . = 'Gedung Bertingkat Dijual')]</value>
      <webElementGuid>b2c4cc02-7715-4439-992c-07595f5f4122</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
