<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_BandungKotaKabupaten Di Jawa Barat, IndonesiaKotaKabupaten</name>
   <tag></tag>
   <elementGuidId>4f13e04b-af1a-4259-93da-a5d9d8fb9032</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;&lt;strong>Bandung&lt;/strong>&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/section/form/div[2]/div[2]/div[2]/div[2]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3d50d8ef-e8b1-442a-97c3-f4a5826fc2aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.99.co/id/jual/rumah/bandung</value>
      <webElementGuid>bfffb73e-085d-4de8-8a89-dfb06f518c5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>&lt;strong>Bandung&lt;/strong></value>
      <webElementGuid>2b68e1e0-c2f9-436a-9c00-26d16add8db0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BandungKota/Kabupaten Di Jawa Barat, IndonesiaKota/Kabupaten</value>
      <webElementGuid>80d95ec7-6f25-4dcc-9c34-86d1b91478e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;homePage&quot;]/section[@class=&quot;banner&quot;]/form[@class=&quot;searchBarHome&quot;]/div[@class=&quot;searchBarHome--main&quot;]/div[@class=&quot;searchBarHome--main__col&quot;]/div[@class=&quot;ui-molecules-search-bar&quot;]/div[@class=&quot;ui-molecules-search-bar__suggestions&quot;]/div[@class=&quot;ui-molecules-search-bar__suggestions-wrapper&quot;]/a[1]</value>
      <webElementGuid>b1e819ea-5a5a-4df4-bb8a-e199d555e9e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section/form/div[2]/div[2]/div[2]/div[2]/div/a</value>
      <webElementGuid>e35e54c2-0e53-4156-8b5b-2dd5190acd62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.99.co/id/jual/rumah/bandung')]</value>
      <webElementGuid>29d3e576-5610-4d98-934e-b2974f78f93b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div/a</value>
      <webElementGuid>7722460a-e06e-49d3-b77a-3e65dc3a8feb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.99.co/id/jual/rumah/bandung' and @title = '&lt;strong>Bandung&lt;/strong>' and (text() = 'BandungKota/Kabupaten Di Jawa Barat, IndonesiaKota/Kabupaten' or . = 'BandungKota/Kabupaten Di Jawa Barat, IndonesiaKota/Kabupaten')]</value>
      <webElementGuid>ff97bd43-0bd3-4999-8488-93bcf9ef1272</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
