<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Lokasi TerkaitBaliProvins</name>
   <tag></tag>
   <elementGuidId>c6e8cb38-10e7-4448-b3e4-00bae3bf92ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ui-molecules-search-bar__suggestions</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/section/form/div[2]/div[2]/div[2]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0342239b-0c2a-494f-bd93-e102639155d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-molecules-search-bar__suggestions</value>
      <webElementGuid>0c850e94-4823-4e53-9736-1e25662f732d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lokasi TerkaitBaliProvinsi Di IndonesiaProvinsiBantenProvinsi Di IndonesiaProvinsiJawa BaratProvinsi Di IndonesiaProvinsiPapua BaratProvinsi Di IndonesiaProvinsiSumatera BaratProvinsi Di IndonesiaProvinsiSulawesi BaratProvinsi Di IndonesiaProvinsiKalimantan BaratProvinsi Di IndonesiaProvinsiNusa Tenggara BaratProvinsi Di IndonesiaProvinsiKepulauan Bangka BelitungProvinsi Di IndonesiaProvinsiBandung BaratKota/Kabupaten Di Jawa Barat, IndonesiaKota/Kabupaten</value>
      <webElementGuid>d5306f0e-af60-4e97-9060-648d1eee2889</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;homePage&quot;]/section[@class=&quot;banner&quot;]/form[@class=&quot;searchBarHome&quot;]/div[@class=&quot;searchBarHome--main&quot;]/div[@class=&quot;searchBarHome--main__col&quot;]/div[@class=&quot;ui-molecules-search-bar&quot;]/div[@class=&quot;ui-molecules-search-bar__suggestions&quot;]</value>
      <webElementGuid>d71c57e2-a3d9-460a-83ec-32b177475dd5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section/form/div[2]/div[2]/div[2]/div[2]</value>
      <webElementGuid>dce46739-df87-48d6-a084-62d06055bdb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div[2]</value>
      <webElementGuid>c894adba-9b2e-4300-99c7-f28af3a5eeb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Lokasi TerkaitBaliProvinsi Di IndonesiaProvinsiBantenProvinsi Di IndonesiaProvinsiJawa BaratProvinsi Di IndonesiaProvinsiPapua BaratProvinsi Di IndonesiaProvinsiSumatera BaratProvinsi Di IndonesiaProvinsiSulawesi BaratProvinsi Di IndonesiaProvinsiKalimantan BaratProvinsi Di IndonesiaProvinsiNusa Tenggara BaratProvinsi Di IndonesiaProvinsiKepulauan Bangka BelitungProvinsi Di IndonesiaProvinsiBandung BaratKota/Kabupaten Di Jawa Barat, IndonesiaKota/Kabupaten' or . = 'Lokasi TerkaitBaliProvinsi Di IndonesiaProvinsiBantenProvinsi Di IndonesiaProvinsiJawa BaratProvinsi Di IndonesiaProvinsiPapua BaratProvinsi Di IndonesiaProvinsiSumatera BaratProvinsi Di IndonesiaProvinsiSulawesi BaratProvinsi Di IndonesiaProvinsiKalimantan BaratProvinsi Di IndonesiaProvinsiNusa Tenggara BaratProvinsi Di IndonesiaProvinsiKepulauan Bangka BelitungProvinsi Di IndonesiaProvinsiBandung BaratKota/Kabupaten Di Jawa Barat, IndonesiaKota/Kabupaten')]</value>
      <webElementGuid>a408fd17-dafa-489e-be9d-d3307c843afd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
