<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_rumah</name>
   <tag></tag>
   <elementGuidId>961b43f8-3525-4e7d-8439-11b0823d4088</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.truncated</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/section/form/div[2]/div/div[2]/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>38d15b46-e7a9-4bd1-b2e4-b80faf6ef0c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>truncated</value>
      <webElementGuid>d6396ad6-533f-439f-a71e-ff25fe9c3153</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>rumah</value>
      <webElementGuid>bdac37e1-4b77-488a-9fd4-4d80e0574fca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;homePage&quot;]/section[@class=&quot;banner&quot;]/form[@class=&quot;searchBarHome&quot;]/div[@class=&quot;searchBarHome--main&quot;]/div[@class=&quot;searchBarHome--main__col&quot;]/div[@class=&quot;ui-molecules-select searchBarHome--main__filter_select&quot;]/div[@class=&quot;ui-molecules-select__field-value has-value&quot;]/span[@class=&quot;truncated&quot;]</value>
      <webElementGuid>dd4ad474-aca1-464f-a9a0-a94ca1f0f38f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section/form/div[2]/div/div[2]/div/span</value>
      <webElementGuid>c4e62eb1-d678-4166-bd8d-25280ed31b5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/span</value>
      <webElementGuid>37493174-6653-41b8-bbe1-09f22e711006</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'rumah' or . = 'rumah')]</value>
      <webElementGuid>a97b7858-a5d0-4cdb-8ba7-32a0653a835d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
